# Generated by Django 3.1 on 2020-09-27 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=100)),
                ('org_name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('FOOD', 'Food'), ('CLOTHING', 'Clothing'), ('ADDICTION_RECOVERY', 'Addiction Recovery'), ('HYGIENE', 'Hygiene'), ('FINANCIAL_EMPOWERMENT', 'Financial Empowerment'), ('SHELTER', 'Shelter'), ('WOMEN_AND_CHILDREN', 'Women and Children'), ('MENTAL_HEALTH_SERVICES', 'Mental Health Services'), ('FINANCIAL_EMPOWERMENT', 'Financial Empowerment'), ('MEDICAL_ASSISTANCE', 'Medical Assistance')], default='UNKNOWN', max_length=100)),
                ('opening_hours', main_app.models.WeeklyOpeningHoursField(default='', max_length=512)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('street_number', models.CharField(blank=True, max_length=100)),
                ('street_name', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('long', models.DecimalField(decimal_places=6, max_digits=12)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=12)),
                ('phone', models.CharField(max_length=16)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True, max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
