# Generated by Django 3.0.7 on 2020-08-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='location',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='phone',
        ),
        migrations.AddField(
            model_name='resource',
            name='lat',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='resource',
            name='long',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
    ]
