# Generated by Django 3.1 on 2020-10-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
