# Generated by Django 3.0.7 on 2020-08-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200823_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='resource',
            name='long',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=8),
        ),
    ]
