# Generated by Django 3.0.8 on 2020-12-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201011_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='seniors_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='youth_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='lat',
            field=models.DecimalField(decimal_places=32, max_digits=64),
        ),
        migrations.AlterField(
            model_name='resource',
            name='long',
            field=models.DecimalField(decimal_places=32, max_digits=64),
        ),
    ]
