# Generated by Django 3.1 on 2020-09-06 19:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_resource_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('FOOD', 'Food'), ('CLOTHING', 'Clothing'), ('ADDICTION_RECOVERY', 'Addiction Recovery'), ('HYGIENE', 'Hygiene'), ('FINANCIAL_EMPOWERMENT', 'Financial Empowerment'), ('SHELTER', 'Shelter'), ('WOMEN_AND_CHILDREN', 'Women and Children'), ('MENTAL_HEALTH_SERVICES', 'Mental Health Services'), ('FINANCIAL_EMPOWERMENT', 'Financial Empowerment'), ('MEDICAL_ASSISTANCE', 'Medical Assistance')], default='UNKNOWN', max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
