# Generated by Django 3.0.7 on 2020-10-04 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200927_2310'),
        ('main_app', '0005_resource_phone'),
    ]

    operations = [
    ]
