# Generated by Django 3.0.7 on 2020-10-04 21:00

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_merge_20201004_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='street',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='hours',
        ),
        migrations.AddField(
            model_name='resource',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resource',
            name='opening_hours',
            field=main_app.models.WeeklyOpeningHoursField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='resource',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='resource',
            name='street_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resource',
            name='street_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('FOOD', 'Food'), ('CLOTHING', 'Clothing'), ('ADDICTION_RECOVERY', 'Addiction Recovery'), ('HYGIENE', 'Hygiene'), ('FINANCIAL_EMPOWERMENT', 'Financial Empowerment'), ('SHELTER', 'Shelter'), ('WOMEN_AND_CHILDREN', 'Women and Children'), ('MENTAL_HEALTH_SERVICES', 'Mental Health Services'), ('FINANCIAL_EMPOWERMENT', 'Financial Empowerment'), ('MEDICAL_ASSISTANCE', 'Medical Assistance')], default='UNKNOWN', max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='resource',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='resource',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
