# Generated by Django 3.1 on 2020-09-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200906_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='street',
            new_name='street_name',
        ),
        migrations.AddField(
            model_name='resource',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resource',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='resource',
            name='street_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
